# Generated by Django 3.2.6 on 2021-09-03 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orderUpdate',
        ),
    ]
